apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: go-sample
    app.kubernetes.io/name: go-sample
  name: go-sample-metrics
  namespace: sample
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 80
    protocol: TCP
    targetPort: 8088
  selector:
    app: go-server
  sessionAffinity: None
  type: ClusterIP

